name: Run prediction vs reality comparison

on:
  schedule:
    - cron: "0 22 * * *"   # Runs at 22
  workflow_dispatch:        # Allows manual triggering of the workflow

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install huggingface_hub jupyter nbconvert nbclient joblib pandas numpy matplotlib requests prophet scikit-learn cloudpickle
 

      - name: Authenticate with Hugging Face
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          echo "Authenticating with Hugging Face..."
          huggingface-cli login --token "${{ secrets.HUGGINGFACE_TOKEN }}"

      - name: Verify Hugging Face Authentication
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          huggingface-cli whoami

      - name: Run Jupyter Notebook
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          jupyter nbconvert --to notebook --execute comparison_update/comparison_pred_reality.ipynb \
          --output executed_notebook.ipynb

      - name: Upload executed notebook as artifact
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: executed_notebook.ipynb
