name: Run Notebook Hourly

on:
  schedule:
    - cron: "0 7-21 * * *"   # Runs every hour from 7 AM to 9 PM
  workflow_dispatch:    # Allows manual triggering of the workflow

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install huggingface_hub jupyter nbconvert nbclient

      - name: Authenticate with Hugging Face
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          echo "Authenticating with Hugging Face..."
          huggingface-cli login --add-to-git-credential --token "${{ secrets.HUGGINGFACE_TOKEN }}"

      - name: Verify Hugging Face Token
        run: |
          huggingface-cli whoami
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

      - name: Run Jupyter Notebook
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          jupyter nbconvert --to notebook --execute training_inference/OBT_3_inference.ipynb \
          --output executed_notebook.ipynb --stdout

      - name: Upload executed notebook as artifact
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: executed_notebook.ipynb
