name: Run Jupyter Notebook Inference

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # You can set the desired Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install huggingface_hub jupyter nbconvert nbclient joblib pandas numpy matplotlib requests prophet

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute training_inference/OBT_3_inference.ipynb --output result.ipynb
      env:
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

    - name: Upload executed notebook
      uses: actions/upload-artifact@v3
      with:
        name: executed-notebook
        path: training_inference/result.ipynb

    - name: Debug - Check installed packages
      if: ${{ failure() }}
      run: pip freeze
