name: Run Notebook

on:
  workflow_dispatch:    # Permette di avviare manualmente il workflow

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: List files in scraper_days
        run: ls -R scraper_days

      - name: Show notebook content
        run: cat scraper_days/scraper_kth_days.ipynb

      - name: Install dependencies
        run: |
          pip install -r scraper_days/requirements.txt
          pip install jupyter nbconvert nbformat

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute scraper_days/scraper_kth_days.ipynb --output scraper_days/executed_notebook.ipynb
