name: Run Scrape Opening Hours

on:
  workflow_dispatch:    # Allows manual triggering of the workflow
  schedule:
    - cron: "0 9 * * 1,3,5"   # Runs at 9:00 AM UTC on Monday, Wednesday, and Friday

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install jupyter nbconvert nbclient huggingface_hub matplotlib numpy pandas requests datasets joblib
      

      - name: Run Jupyter Notebook
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          jupyter nbconvert --to notebook --execute scraper_days/scraper_kth_days.ipynb \
          --output executed_notebook.ipynb --stdout

      - name: Upload executed notebook as artifact
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: executed_notebook.ipynb
